#: import TabbedPanel kivy.uix.tabbedpanel
<ErrorPopup>:
  size_hint: .5, .5
  auto_dismiss: False
  title: 'Fehler beim Login'

  Label:
    text: 'Fehler beim Username/Password!'
  Button:
    text: 'Zurück zum Login.'
    on_press: root.dismiss()



<LoginScreen>:
  username: username_input
  password: password_input
  login_button: login_button

  AnchorLayout:
    anchor_x: 'center'
    anchor_y: 'center'

    GridLayout:
      row_force_default: True
      row_default_height: 40
      col_default_width: 120
      size_hint: None, None

      width: self.minimum_width
      height: self.minimum_height

      cols: 2

      Label:
        text: 'Username'
      TextInput:
        id: username_input
        multiline: False
        write_tab: False

      Label:
        text: 'Password'
      TextInput:
        id: password_input
        password: True
        multiline: False
        write_tab: False

      Button:
        id: login_button
        text: 'Login'
        on_press: root.AttemptLogin()

      Button:
        text: 'Registrieren'
        on_press: root.manager.current = 'registrierung'







<MainScreen>:
  BoxLayout:
    size_hint_x: .5
    height: 40

    BoxLayout:

      orientation: 'vertical'
      Button:
        text: 'Stammdaten'
        on_press: root.manager.current = 'stammdaten'

      Button:
        text: 'Labortagebuch'

      Button:
        text: 'Ergebnisse'

      Button:
        text: 'Bericht erstellen'

      Button:
        text: 'Logout'
        on_press: root.manager.current = 'login'

    BoxLayout:
      ListView:










<Registrierung>:

  registrierung_username: registrierung_username_input
  registrierung_password: registrierung_password_input
  BoxLayout:
    orientation: 'vertical'
    Label:
      text: 'Username und Passwort eingeben!'
    GridLayout:
      row_force_default: True
      row_default_height: 40

      cols: 2

      Label:
        text: 'Username'
      TextInput:
        id: registrierung_username_input
        multiline: False
        write_tab: False
        focused: True

      Label:
        text: 'Passwort'
      TextInput:
        id: registrierung_password_input
        multiline: False
        write_tab: False
        focused: True
        password: True

      Button:
        text: 'Speichern'
      Button:
        text: 'Zurück'
        on_press: root.manager.current = 'login'


<Stammdaten>:
  BoxLayout:

    size_hint: .5, .5
    do_default_tab: False
    BoxLayout:
      orientation: 'vertical'

      Button:
        text: 'Kundenadresse'
        on_press: root.manager.current = 'stammdaten_kundenadresse'
      Button:
        text: 'DGHM Richtwerte'
      Button:
        text: 'DGHM Warnwerte'

      Button:
        text: 'Leitsätze'



      Button:
        text: 'Zurück zum Hauptmenü'
        on_press: root.manager.current = 'main'

    BoxLayout:

<StammdatenKundenadresse>:
  kundenname: kundenname_input
  adresse: adresse_input

  BoxLayout:
    size_hint: .5, .5
    do_default_tab: False
    BoxLayout:
      orientation: 'vertical'

      Button:
        text: 'Stammdaten'
        on_press: root.manager.current = 'stammdaten'

      Button:
        text: 'Zurück zum Hauptmenü'
        on_press: root.manager.current = 'main'

    GridLayout:
      row_force_default: True
      row_default_height: 40
      cols: 2

      Label:
        text: 'Kundenname: '
      TextInput:
        id: kundenname_input
        multiline: False
        write_tab: False
        focused: True
      Label:
        text: 'Adresse 1: '
      TextInput:
        id: adresse_input
        multiline: False
        write_tab: False
        focused: True











<Manager>:
  id: screen_manager

  login_screen: login_screen
  main_screen: main_screen
  registrierung: registrierung_screen
  stammdaten: stammdaten_screen
  stammdaten_kundenadresse: stammdaten_kundenadresse_screen


  LoginScreen:
    id: login_screen
    name: 'login'
    manager: screen_manager

  MainScreen:
    id: main_screen
    name: 'main'
    manager: screen_manager

  Registrierung:
    id: registrierung_screen
    name: 'registrierung'
    manager: screen_manager

  Stammdaten:
    id: stammdaten_screen
    name: 'stammdaten'
    manager: screen_manager

  StammdatenKundenadresse:
    id: stammdaten_kundenadresse_screen
    name: 'stammdaten_kundenadresse'
    manager: screen_manager
